# Generated by Django 3.0.7 on 2021-06-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eShopReact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coustomer',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='coustomer',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coustomer',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coustomer',
            name='zip',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coustomer',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coustomer',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coustomer',
            name='password',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='coustomer',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
