# Generated by Django 3.0.7 on 2021-06-06 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eShopReact', '0002_auto_20210605_2008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coustomer',
            new_name='Customer',
        ),
    ]
